In [22]:
'''
Write a python program to compute the sum of the two reversed numbers and display the sum in reversed form.
Input: 13, 14
Output: 27
Note: The result will not be unique for every number for example 31 is a reversed form of several numbers of 13, 130, 1300 etc.
Therefore all the leading zeros will be omitted. 
'''
def sum_reverse_number(num1: int, num2: int) -> int:
    num1 = int(str(num1)[::-1])
    num2 = int(str(num2)[::-1])
    return int(str(num1+num2)[::-1])

In [10]:
sum_reverse_number(13, 14)

27

In [18]:
sum_reverse_number(15, 19)

241

In [11]:
sum_reverse_number(1300, 14)

27

In [23]:
'''
Write a python program to check whether a given number is an ugly number
Input: 12
Output: True
Ugly numbers are positive numbers whose only prime factors are 2, 3, or 5.
The sequence 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, ....
Note: 1 is typically treated as an ugly number
'''
def is_ugly(num: int) -> bool:
    if num <= 0:
        return False
    elif num == 1:
        return True
    factor = [2, 3, 5]
    for i in factor:
        while num%i == 0:
            num /= i
    return num == 1


In [24]:
is_ugly(12)

True

In [25]:
is_ugly(11)

False

In [1]:
import nltk

In [2]:
text = "Can you please buy me an Arizona Ice Tea? It is $0.99."

In [9]:
from nltk.tokenize import word_tokenize
token = word_tokenize(text)

In [10]:
token

['Can',
 'you',
 'please',
 'buy',
 'me',
 'an',
 'Arizona',
 'Ice',
 'Tea',
 '?',
 'It',
 'is',
 '$',
 '0.99',
 '.']

In [12]:
# https://www.guru99.com/pos-tagging-chunking-nltk.html#:~:text=Summary,each%20word%20of%20the%20sentence.
print(f"parts of the speech: {nltk.pos_tag(token)}")

parts of the speech: [('Can', 'MD'), ('you', 'PRP'), ('please', 'VB'), ('buy', 'VB'), ('me', 'PRP'), ('an', 'DT'), ('Arizona', 'NNP'), ('Ice', 'NNP'), ('Tea', 'NNP'), ('?', '.'), ('It', 'PRP'), ('is', 'VBZ'), ('$', '$'), ('0.99', 'CD'), ('.', '.')]


### Bag-of-Words

In [20]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
text_data = np.array(['I love Brazil. Brazil!', 'Sweden is best', 'Germany beats both'])

In [15]:
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

In [18]:
bag_of_words

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [25]:
import warnings
warnings.filterwarnings('ignore')

In [26]:
count.get_feature_names()

['beats', 'best', 'both', 'brazil', 'germany', 'is', 'love', 'sweden']

In [23]:
bag_of_words.toarray()

array([[0, 0, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 0]])

In [27]:
df = pd.DataFrame(bag_of_words.toarray(), columns=count.get_feature_names())

In [28]:
df.head()

beats  best  both  brazil  germany  is  love  sweden
0      0     0     0       2        0   0     1       0
1      0     1     0       0        0   1     0       1
2      1     0     1       0        1   0     0       0

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
tfidf = TfidfVectorizer()
feature_matrix = tfidf.fit_transform(text_data)

In [31]:
feature_matrix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [32]:
feature_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

In [35]:
df = pd.DataFrame(feature_matrix.toarray(), columns=tfidf.get_feature_names())
df.head()

beats     best     both    brazil  germany       is      love   sweden
0  0.00000  0.00000  0.00000  0.894427  0.00000  0.00000  0.447214  0.00000
1  0.00000  0.57735  0.00000  0.000000  0.00000  0.57735  0.000000  0.57735
2  0.57735  0.00000  0.57735  0.000000  0.57735  0.00000  0.000000  0.00000

In [41]:
# Word index for toarray()
tfidf.vocabulary_

{'love': 6,
 'brazil': 3,
 'sweden': 7,
 'is': 5,
 'best': 1,
 'germany': 4,
 'beats': 0,
 'both': 2}

In [39]:
feature_matrix.toarray()

array([[0.        , 0.        , 0.        , 0.89442719, 0.        ,
        0.        , 0.4472136 , 0.        ],
       [0.        , 0.57735027, 0.        , 0.        , 0.        ,
        0.57735027, 0.        , 0.57735027],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027,
        0.        , 0.        , 0.        ]])

### In class Assignment-3

In [115]:
text1 = 'Feature Extraction aims to reduce the number of features in a dataset by creating new features from the existing ones (and then discarding the original features). These new reduced set of features should then be able to summarize most of the information contained in the original set of features!!!. In this way, a summarised version of the original features can be created from a combination of the original set!!!'
text2 = 'Another commonly used technique to reduce the number of feature in a dataset is Feature Selection! The difference between Feature Selection and/or Feature Extraction is that feature selection aims instead to $ rank the importance of the existing features in the dataset and discard less important ones (no new features are created)?!. If you are interested in finding out more about Feature Selection, you can find more information about it in my previous article.'
text3 = 'In this article, I will walk you through how to apply Feature Extraction techniques using the Kaggle Mushroom Classification Dataset as an example??? Our objective will be to try to predict if a Mushroom is poisonous or not by looking at the given features. All the code used in this post (and more!) is available on Kaggle and on my GitHub Account.'

In [116]:
from nltk.corpus import stopwords

In [117]:
stopwords = set(stopwords.words("english"))

In [118]:
import re
# remove punctuation from text
def remove_punctuation(text):
    text = re.sub(r'[^\w\s]', '', text)
    return text

In [119]:
text1 = remove_punctuation(text1)
text2 = remove_punctuation(text2)
text3 = remove_punctuation(text3)

In [120]:
text1_tokenize = word_tokenize(text1)
text2_tokenize = word_tokenize(text2)
text3_tokenize = word_tokenize(text3)

In [121]:
# remove stopwods from text
def remove_stopwords(text: list) -> list:
    text_list = [word for word in text if word.lower() not in stopwords]
    return text_list

In [122]:
text1_stopwords = remove_stopwords(text1_tokenize)
text2_stopwords = remove_stopwords(text2_tokenize)
text3_stopwords = remove_stopwords(text3_tokenize)

In [123]:
from nltk.stem  import PorterStemmer
porter = PorterStemmer()

In [124]:
def stemmize(text_list: list) -> list:
    new_text_list = []
    for word in text_list:
        word = word.lower()
        new_text_list.append(porter.stem(word))

    return new_text_list

In [125]:
text1_stem = stemmize(text1_stopwords)
text2_stem = stemmize(text2_stopwords)
text3_stem = stemmize(text3_stopwords)

In [126]:
def get_pos_tag(text_list: list) -> list:
    return nltk.pos_tag(text_list)

In [127]:
text1_pos = get_pos_tag(text1_stopwords)
text2_pos = get_pos_tag(text2_stopwords)
text3_pos = get_pos_tag(text3_stopwords)

In [128]:
from nltk.stem import WordNetLemmatizer
word_lem = WordNetLemmatizer()

In [129]:
def word_pos_lemmetize(text_list: list) -> list:
    new_lemmetize_list = []
    for text, tag in text_list:
        text = text.lower()
        if tag.startswith('N'):
            wld = word_lem.lemmatize(text, pos='n')
        elif tag.startswith('V'):
            wld = word_lem.lemmatize(text, pos='v')
        elif tag.startswith('J'):
            wld = word_lem.lemmatize(text, pos='a')
        elif tag.startswith('R'):
            wld = word_lem.lemmatize(text, pos='r')
        else:
            wld = text
        new_lemmetize_list.append(wld)
    return new_lemmetize_list

In [130]:
text1_lem = word_pos_lemmetize(text1_pos)
text2_lem = word_pos_lemmetize(text2_pos)
text3_lem = word_pos_lemmetize(text3_pos)

In [131]:
def convert_list_to_str(text_list: list) -> str:
    str_text = ''
    for i in text_list:
        str_text += i +' '
    return str_text

In [132]:
str_text1 = convert_list_to_str(text1_lem)
str_text2 = convert_list_to_str(text2_lem)
str_text3 = convert_list_to_str(text3_lem)

In [133]:
document = np.array([str_text1, str_text2, str_text3])
document

array(['feature extraction aim reduce number feature dataset create new feature exist one discard original feature new reduce set feature able summarize information contain original set feature way summarise version original feature create combination original set ',
       'another commonly use technique reduce number feature dataset feature selection difference feature selection andor feature extraction feature selection aim instead rank importance exist feature dataset discard less important one new feature create interested finding feature selection find information previous article ',
       'article walk apply feature extraction technique use kaggle mushroom classification dataset example objective try predict mushroom poisonous look give feature code use post available kaggle github account '],
      dtype='<U318')

In [134]:
def get_bag_of_words(document: np.array):
    return count.fit_transform(document)

In [135]:
bag_of_words = get_bag_of_words(document=document)

In [136]:
df_bg = pd.DataFrame(bag_of_words.toarray(), columns=count.get_feature_names())
df_bg.head()

able  account  aim  andor  another  apply  article  available  \
0     1        0    1      0        0      0        0          0   
1     0        0    1      1        1      0        1          0   
2     0        1    0      0        0      1        1          1   

   classification  code  ...  selection  set  summarise  summarize  technique  \
0               0     0  ...          0    3          1          1          0   
1               0     0  ...          4    0          0          0          1   
2               1     1  ...          0    0          0          0          1   

   try  use  version  walk  way  
0    0    0        1     0    1  
1    0    1        0     0    0  
2    1    2        0     1    0  

[3 rows x 55 columns]

In [137]:
def get_tfidf(document: np.array):
    return tfidf.fit_transform(document)

In [138]:
tfidf_ = get_tfidf(document)

In [139]:
tfidf_

<3x55 sparse matrix of type '<class 'numpy.float64'>'
	with 73 stored elements in Compressed Sparse Row format>

In [140]:
df_tfidf = pd.DataFrame(tfidf_.toarray(), columns=tfidf.get_feature_names())
df_tfidf.head()

able   account       aim     andor   another     apply   article  \
0  0.128883  0.000000  0.098019  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.098175  0.129089  0.129089  0.000000  0.098175   
2  0.000000  0.187109  0.000000  0.000000  0.000000  0.187109  0.142301   

   available  classification      code  ...  selection      set  summarise  \
0   0.000000        0.000000  0.000000  ...   0.000000  0.38665   0.128883   
1   0.000000        0.000000  0.000000  ...   0.516355  0.00000   0.000000   
2   0.187109        0.187109  0.187109  ...   0.000000  0.00000   0.000000   

   summarize  technique       try       use   version      walk       way  
0   0.128883   0.000000  0.000000  0.000000  0.128883  0.000000  0.128883  
1   0.000000   0.098175  0.000000  0.098175  0.000000  0.000000  0.000000  
2   0.000000   0.142301  0.187109  0.284603  0.000000  0.187109  0.000000  

[3 rows x 55 columns]